version: '3.3'

services:
  prometheus:
    container_name: pix-prometheus
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    networks:
      - backend
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    container_name: pix-grafana
    image: grafana/grafana
    restart: always
    networks:
      - backend
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_HTTP_PORT=3000
      - GF_ADMIN_USER=grafana
      - GF_ADMIN_PASSWORD=grafana
    depends_on:
      - prometheus

networks:
  backend: