version: "3.3"

services:
  itau:
    container_name: banco-itau
    build:
      context: ./BancoItau
      dockerfile: Dockerfile
    restart: always
    networks:
      - backend
    depends_on:
      - eureka

  bacen:
    container_name: bacen
    build:
      context: ./bacen
      dockerfile: Dockerfile
    restart: always
    networks:
      - backend
    depends_on:
      - eureka

  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

    networks:
     - backend

    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - backend

  eureka:
    container_name: eureka
    build:
      context: ./eureka
      dockerfile: Dockerfile
    restart: always
    networks:
      - backend

networks:
  backend: