global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "projeto-pix"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ host.docker.internal:8080, host.docker.internal:8081 ]
        labels:
          application: "projeto-pix"